# Generated by Django 3.0.8 on 2021-03-25 11:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner',
            fields=[
                ('oId', models.AutoField(primary_key=True, serialize=False)),
                ('oFname', models.CharField(max_length=100)),
                ('oLname', models.CharField(max_length=100)),
                ('oEmail', models.EmailField(max_length=254, unique=True)),
                ('oPassword', models.CharField(max_length=128)),
                ('oMobile', models.BigIntegerField()),
                ('oDOB', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Rooms',
            fields=[
                ('rId', models.AutoField(primary_key=True, serialize=False)),
                ('rPrice', models.IntegerField()),
                ('rAddress', models.CharField(max_length=100)),
                ('rCity', models.CharField(max_length=100)),
                ('rState', models.CharField(max_length=100)),
                ('rShare', models.IntegerField()),
                ('rGirlsOnly', models.BooleanField(default=False)),
                ('rOid', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.Owner')),
            ],
        ),
    ]
