# Generated by Django 3.0.8 on 2021-03-25 18:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20210325_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='oGender',
            field=models.CharField(default='M', max_length=4),
            preserve_default=False,
        ),
    ]
