# Generated by Django 3.0.8 on 2021-03-25 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_owner_ogender'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='oDOB',
            field=models.CharField(max_length=15),
        ),
    ]
