# Generated by Django 3.0.8 on 2021-03-25 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_auto_20210326_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='oDOB',
            field=models.DateField(),
        ),
    ]
