# Generated by Django 3.1.7 on 2021-04-18 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_auto_20210414_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='rProfile',
            field=models.ImageField(null=True, upload_to='rooms/'),
        ),
    ]
