# Generated by Django 3.1.7 on 2021-04-18 12:37

from django.db import migrations, models
import main.models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_auto_20210418_1733'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='rPic',
            field=models.ImageField(null=True, upload_to=main.models.path_and_rename),
        ),
    ]
