# Generated by Django 3.1.7 on 2021-04-18 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_owner_orooms'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner',
            name='oProfile',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
