# Generated by Django 3.2 on 2021-04-22 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0011_owner_oprofile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='oGender',
            field=models.CharField(max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='oProfile',
            field=models.ImageField(default='null', null=True, upload_to=''),
        ),
    ]
