# Generated by Django 3.2 on 2021-04-22 15:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_auto_20210422_2117'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='oProfile',
            field=models.ImageField(default='null', upload_to=''),
        ),
    ]
